---

- name: ExamplePlaybook
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks:
    - name: Include Variables
      include_vars: "{{ item }}"
      with_items:
        - "vars.yml"
        - "secrets.yml"
      tags: always

  roles:
    - { role: "ansible-basic-server-setup", when: skip_basic_server_setup is not defined or ( skip_basic_server_setup is defined and skip_basic_server_setup == false ) }
